# Generated by Django 5.0.6 on 2024-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Only Me', 'Only Me')], default='public', max_length=50),
        ),
    ]
