# Generated by Django 5.0.6 on 2024-05-22 08:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_cover_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/cover_x5yc8e.jpg', max_length=255, null=True, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/default_lelg4l.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
