# Generated by Django 5.0.6 on 2024-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_alter_profile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/cover_x5yc8e.jpg', max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/default_lelg4l.jpg', max_length=255, null=True, upload_to=''),
        ),
    ]
