# Generated by Django 5.0.6 on 2024-07-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roomvideocall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomVideoCall',
        ),
    ]
