# Generated by Django 5.0.6 on 2024-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_roomvideocall'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
